name: Monitor GitHub Followers
description: Monitor GitHub Followers
inputs:
  issue_number:
    description: |
      GitHub Issue Number to notify
    required: true
  login:
    description: |
      GitHub user login. By default, it's the current repository's owner.
    required: false
  notify_decrease:
    description: |
      The value must be "true" or "false".
      If "true", it notifies if followers are decreased.
    required: false
    default: "true"
  github_token:
    description: |
      GitHub Access Token.
      issues:write and packages:write permissions are required.
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # Install oras
    - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
      with:
        aqua_version: v2.44.1
        skip_install_aqua: "true"
        enable_aqua_install: "false"
    - run: aqua -c "$GITHUB_ACTION_PATH/aqua/aqua.yaml" exec -- oras version
      shell: bash
    - run: |
        echo "$GITHUB_TOKEN" |
          aqua -c "$GITHUB_ACTION_PATH/aqua/aqua.yaml" exec -- \
            oras login -u octokit --password-stdin ghcr.io
      shell: bash
      env:
        GITHUB_TOKEN: ${{github.token}}
    # Pull the last result from GitHub Container Registry using oras
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        aqua -c "$GITHUB_ACTION_PATH/aqua/aqua.yaml" exec -- \
          oras pull "ghcr.io/$GITHUB_REPOSITORY/followers.json:latest"
    # List followers by GraphQL API
    # Compare
    # Post a comment to an issue if followers are changed
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        LOGIN: ${{ inputs.login }}
        NOTIFY_DECREASE: ${{ inputs.notify_decrease }}
      run: |
        node "${GITHUB_ACTION_PATH}/dist/index.js"
    # Push the last result to GitHub Container Registry using oras
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mv latest-followers.json followers.json
        aqua -c "$GITHUB_ACTION_PATH/aqua/aqua.yaml" exec -- \
          oras push "ghcr.io/$GITHUB_REPOSITORY/followers.json:latest" followers.json
