---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.41.0
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: actionlint -ignore 'file "dist/index.js" does not exist'
