name: Update the latest branch
on:
  push:
    branches:
      - main
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run build
      - uses: suzuki-shunsuke/release-js-action@0696e3fc3386d4f3d2dfd9e194e8e14052cea99d # v0.1.4
        with:
          version: latest
