---
name: Watch Followers
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '/5 0 * * *'
jobs:
  watch-follower:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: suzuki-shunsuke/monitor-gh-follower-action@7b73d26bc90deb4b26597b5344eba9f738c80e6f # v0.1.0-0
        with:
          issue_number: 1
