---
name: Watch Followers
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '/5 0 * * *'
jobs:
  watch-follower:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      issues: write
      packages: write
    steps:
      - uses: suzuki-shunsuke/monitor-gh-follower-action@322f4b4fca1d7cdcfec623bc3ae8c08393d00f49 # v0.1.0-5
        with:
          issue_number: 1
