---
name: Watch Followers
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '/5 0 * * *'
jobs:
  watch-follower:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      issues: write
      packages: write
    steps:
      - uses: suzuki-shunsuke/monitor-gh-follower-action@76e6aee80e1515b5bf78048fcbd173444d5b3529 # v0.1.0-4
        with:
          issue_number: 1
